laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('perfil', array('as' => 'perfil', 'uses' => 'PerfilController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));

Route::get('trocarIdioma/{lang?}', function($lang = ''){
	
	if($lang == 'pt')
		Session::put('idioma', 'pt');
	elseif($lang == 'en')
		Session::put('idioma', 'en');
	
	return Redirect::back();
});

Route::get('portfolio/{categoria?}/{projeto?}', array('as' => 'portfolio', 'uses' => 'PortfolioController@index'));
Route::get('clientes', array('as' => 'clientes', 'uses' => 'ClientesController@index'));
Route::get('parceiros', array('as' => 'parceiros', 'uses' => 'ParceirosController@index'));
Route::get('clippings/impressos/', array('as' => 'clippings.impressos', 'uses' => 'ClippingsImpressosController@index'));
Route::get('clippings/noshadow/{id}', array('as' => 'clippings.noshadow', 'uses' => 'ClippingsImpressosController@noShadow'));
Route::get('clippings/digitais', array('as' => 'clippings.digitais', 'uses' => 'ClippingsDigitaisController@index'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('banners', 'Painel\BannersController');
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('perfil', 'Painel\PerfilController');
    Route::resource('portfolio', 'Painel\PortfolioController');
    Route::resource('imagens', 'Painel\PortfolioImagensController');
    Route::resource('clientes', 'Painel\ClientesController');
    Route::resource('parceiros', 'Painel\ParceirosController');
    Route::resource('clippingImpresso', 'Painel\ClippingImpressoController');
    Route::resource('clippingImpressoImagens', 'Painel\ClippingImpressoImagensController');
    Route::resource('clippingDigital', 'Painel\ClippingDigitalController');
    Route::resource('contato', 'Painel\ContatoController');
});


Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);
	if(Auth::attempt($authvars)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

laravel/app/controllers/painel/AjaxController.php
<?php

// Namespace
namespace Painel;

// Core
use Request, Input, DB;

// Models

// BaseClass
use Controller;

class AjaxController extends Controller {

	public function __construct(){

	}

	/**
	 * Atualiza a ordem dos itens da tabela
	 *
	 * @return void
	 */
	function gravaOrdem(){
		/* Só aceita requisições feitas via AJAX */
		if(Request::ajax()){
			$menu = Input::get('data');
			$tabela = Input::get('tabela');

	        for ($i = 0; $i < count($menu); $i++) {
	        	DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
	        }
	        return json_encode($menu);
    	}else{
    		return "no-ajax";
    	}
	}

}

laravel/app/controllers/painel/BannersController.php
<?php

// Namespace
namespace Painel;

// Core
use View, Input, Str, Session, Redirect, File;

// Models
use Banner;

// Libs
use Imagine;

class BannersController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.banners.index')->with('banners', Banner::orderBy('ordem', 'ASC')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.banners.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{

		$banner = new Banner;

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');

			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/home/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));

			$imagem->move('assets/images/home/', $filename);
			$banner->imagem = $filename;

			$imagine = new Imagine\Gd\Imagine();
			$sizeOriginal = new Imagine\Image\Box(200,200);
			$mode    = Imagine\Image\ImageInterface::THUMBNAIL_OUTBOUND;

			ini_set('memory_limit','256M');
			$imagine->open('assets/images/home/'.$filename)
					->thumbnail($sizeOriginal, $mode)
					->save('assets/images/home/thumbs/'.$filename, array('quality' => 100));
		}
		$banner->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Banner criado com sucesso.');

		return Redirect::route('painel.banners.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.banners.edit')->with('banner', Banner::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$banner = Banner::find($id);

		if(Input::hasFile('imagem')){
			$imagem = Input::file('imagem');
			
			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/home/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));

			$imagem->move('assets/images/home/', $filename);
			$banner->imagem = $filename;

			$imagine = new Imagine\Gd\Imagine();
			$sizeOriginal = new Imagine\Image\Box(200,200);
			$mode    = Imagine\Image\ImageInterface::THUMBNAIL_OUTBOUND;

			ini_set('memory_limit','256M');
			$imagine->open('assets/images/home/'.$filename)
					->thumbnail($sizeOriginal, $mode)
					->save('assets/images/home/thumbs/'.$filename, array('quality' => 100));
		}
		$banner->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Banner alterado com sucesso.');

		return Redirect::route('painel.banners.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$banner = Banner::find($id);
		$banner->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Banner removido com sucesso.');

		return Redirect::route('painel.banners.index');
	}

}

laravel/app/controllers/painel/BaseAdminController.php
<?php

namespace Painel;

use Controller, View;

class BaseAdminController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

laravel/app/controllers/painel/ClientesController.php
<?php

namespace Painel;

use View, Input, Str, File, Session, Imagine, Redirect, Cliente;

class ClientesController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.clientes.index')->with('clientes', Cliente::orderBy('ordem')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.clientes.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Cliente;

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');
			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/clientes/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));
			$imagem->move('assets/images/clientes/', $filename);
			$object->imagem = $filename;

			ini_set('memory_limit','256M');

			$imagine = new Imagine\Gd\Imagine();
			$resizer = new \Rtablada\Images\ResizeAndPad($imagine);
			$image = $imagine->open('assets/images/clientes/'.$filename);
			$resizer->setSize(220, 160)->apply($image)->save('assets/images/clientes/'.$filename);			
		}

		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Cliente inserido com sucesso.');

		return Redirect::route('painel.clientes.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.clientes.edit')->with('cliente', Cliente::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Cliente::find($id);

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');
			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/clientes/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));
			$imagem->move('assets/images/clientes/', $filename);
			$object->imagem = $filename;

			ini_set('memory_limit','256M');

			$imagine = new Imagine\Gd\Imagine();
			$resizer = new \Rtablada\Images\ResizeAndPad($imagine);
			$image = $imagine->open('assets/images/clientes/'.$filename);
			$resizer->setSize(220, 160)->apply($image)->save('assets/images/clientes/'.$filename, array('quality' => 100));				
		}

		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Cliente alterado com sucesso.');

		return Redirect::route('painel.clientes.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Cliente::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Cliente removido com sucesso.');

		return Redirect::route('painel.clientes.index');
	}

}

laravel/app/controllers/painel/ClippingDigitalController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, ClippingDigital;

class ClippingDigitalController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.clippingDigital.index')->with('clipping', ClippingDigital::orderBy('ordem')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.clippingDigital.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new ClippingDigital;
		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->data = preg_replace("/(\d+)\D+(\d+)\D+(\d+)/","$3-$2-$1",Input::get('data'));
		$object->descricao_pt = Input::get('descricao_pt');
		$object->descricao_en = Input::get('descricao_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Clipping criado com sucesso.');

		return Redirect::route('painel.clippingDigital.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.clippingDigital.edit')->with('clipping', ClippingDigital::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = ClippingDigital::find($id);
		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->data = preg_replace("/(\d+)\D+(\d+)\D+(\d+)/","$3-$2-$1",Input::get('data'));
		$object->descricao_pt = Input::get('descricao_pt');
		$object->descricao_en = Input::get('descricao_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Clipping alterado com sucesso.');

		return Redirect::route('painel.clippingDigital.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = ClippingDigital::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Clipping removido com sucesso.');

		return Redirect::route('painel.clippingDigital.index');
	}

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Contato;

class ContatoController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.contato.index')->with('contato', Contato::orderBy('id')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.contato.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Contato;
		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Informações de contato criadas com sucesso.');

		return Redirect::route('painel.contato.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.contato.edit')->with('contato', Contato::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Contato::find($id);
		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Informações de contato alteradas com sucesso.');

		return Redirect::route('painel.contato.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Contato::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Informações de contato removidas com sucesso.');

		return Redirect::route('painel.contato.index');
	}

}

laravel/app/controllers/painel/HomeController.php
<?php

namespace Painel;

use View;

class HomeController extends BaseAdminController {

    protected $layout = 'painel.template';

	public function index()
	{
		$this->layout->content = View::make('painel.home');
	}

	public function login()
	{
		return View::make('painel.login');
	}

}

laravel/app/views/painel/home.blade.php
@section('conteudo')

	<div class="container">

		<h1>Bem Vindo(a),</h1>

		<br>

		<p>Dia <?=date('d')?> de <?= date('m'), true ?> de <?=date('Y')?>.</p>

		<p>Pelo painel administrativo da trupe você pode controlar as principais funções e conteúdo do site.</p>

		<p>Qualquer Dúvida entrar em contato: <a href="mailto:contato@trupe.net">contato@trupe.net</a></p>

	</div>

@stop

laravel/app/views/painel/login.blade.php
<!DOCTYPE html>
<html lang="pt-BR" class="login">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Painel Administrativo - Debora Aguiar</title>

	<meta name="robots" content="noindex, nofollow" />
	<meta name="author" content="Trupe Design" />
	<meta name="copyright" content="2012 True Design" />
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<base href="{{ url() }}/">
	<script> var BASE = "{{ url() }}"</script>

<?= Assets::CSS(array('painel/css/global', 	'jquery-theme-lightness/jquery-ui-1.8.20.custom')) ?>

<?= Assets::JS(array(
	'libs/modernizr-2.0.6.min',
	'libs/jquery-1.8.0.min',
	'plugins/tinymce/tiny_mce',
	'libs/jquery-ui-1.10.1.custom.min',
	'plugins/jquery.ui.datepicker-pt-BR',
	'plugins/jquery.mtz.monthpicker',
	'plugins/jquery.uploadify.min',
	'plugins/bootstrap',
	'plugins/bootbox.min',
	'scripts/painel'))
?>

</head>
	<body>

		<div class="modal" id="modal-login" style="">

			{{ Form::open( array('route' => 'painel.auth', 'method' => 'post', 'class' => 'form-horizontal') ) }}

			    <div class="modal-header">
			      	<h3 style="text-align:center">
			        	Painel Administrativo <br> Debora Aguiar
			      	</h3>
			    </div>

				<div class="modal-body">

					<fieldset>

						@if(Session::has('login_errors'))
							<div class="alert alert-block alert-error fade in">Usuário ou Senha incorretos</div>
						@endif

				        <div class="control-group">
				        	{{ Form::label('login-username', 'Usuário', array("class" => "control-label")) }}
				          	<div class="controls">
				            	<input class="large validates[required]" required id="login-username" name="username" size="30" type="text" autocomplete="off">
				          	</div>
				        </div>

				        <div class="control-group">
				          	{{ Form::label('login-password', 'Senha', array("class" => "control-label")) }}
				          	<div class="controls">
				            	<input class="large validates[required]" required id="login-password" name="password" size="30" type="password">
				          	</div>
				        </div>

					</fieldset>

				</div>

				<div class="modal-footer">
					{{ Form::submit('Login', array('class' => 'btn btn-primary')) }}
			    </div>

			{{ Form::close() }}

		</div>

	</body>
</html>

laravel/app/views/painel/template.blade.php
<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Painel Administrativo - Debora Aguiar</title>

	<meta name="robots" content="noindex, nofollow" />
	<meta name="author" content="Trupe Design" />
	<meta name="copyright" content="2013 Trupe Design" />
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<base href="{{ url() }}/">
	<script>var BASE = "{{ url() }}"</script>

<?= Assets::CSS(array(
	'painel/css/global',
	'jquery-theme-lightness/jquery-ui-1.8.20.custom'))
?>

<?= Assets::JS(array(
	'libs/modernizr-2.0.6.min',
	'libs/jquery-1.8.0.min',
	'plugins/tinymce/tiny_mce',
	'libs/jquery-ui-1.10.1.custom.min',
	'plugins/jquery.ui.datepicker-pt-BR',
	'plugins/jquery.mtz.monthpicker',
	'plugins/jquery.uploadify.min',
	'plugins/bootstrap',
  'plugins/bootbox.min',
	'scripts/painel'))
?>

</head>
	<body>

	<div class="navbar ">
  		<div class="navbar-inner">

      			<a href="{{ URL::route('painel.home') }}" class="brand">Debora Aguiar</a>

      			<ul class="nav">

        			<li @if(Route::currentRouteName() == 'painel.home') class='active' @endif><a href="{{ URL::route('painel.home') }}">Início</a></li>

              <li @if(str_is('painel.banners*', Route::currentRouteName())) class='active' @endif><a href="{{ URL::route('painel.banners.index') }}">Banners</a></li>

              <li @if(str_is('painel.perfil*', Route::currentRouteName())) class='active' @endif><a href="{{ URL::route('painel.perfil.index') }}">Perfil</a></li>

              <li @if(str_is('painel.portfolio*', Route::currentRouteName()) || str_is('painel.imagens*', Route::currentRouteName())) class='active' @endif><a href="{{ URL::route('painel.portfolio.index') }}">Portfolio</a></li>

              <li @if(str_is('painel.clientes*', Route::currentRouteName())) class='active' @endif><a href="{{ URL::route('painel.clientes.index') }}">Clientes</a></li>

              <li @if(str_is('painel.parceiros*', Route::currentRouteName())) class='active' @endif><a href="{{ URL::route('painel.parceiros.index') }}">Parceiros</a></li>

              <li class="dropdown @if(str_is('painel.clipping*', Route::currentRouteName()))active@endif">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clippings <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ URL::route('painel.clippingImpresso.index') }}">Impressos</a></li>
                    <li><a href="{{ URL::route('painel.clippingDigital.index') }}">Digitais</a></li>
                  </ul>
              </li>

              <li @if(str_is('painel.contato*', Route::currentRouteName())) class='active' @endif><a href="{{ URL::route('painel.contato.index') }}">Contato</a></li>

              <li class="dropdown @if(strpos(Route::currentRouteName(), 'painel.usuarios') !== FALSE)active@endif">
          				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
          				<ul class="dropdown-menu">
            				<li><a href="{{ URL::route('painel.usuarios.index') }}">Usuários</a></li>
            				<li><a href="{{ URL::route('painel.off') }}">Logout</a></li>
          				</ul>
        			</li>

      			</ul>
  		</div>
	</div>

		@yield('conteudo')

		<div id="footer">
    		<hr>
    		<div class="inner">
      			<div class="container">
        			<p class="right">
          				<a href="#">Voltar ao topo</a>
        			</p>
        			<p>
          				&copy; <a href="http://www.trupe.net" target="_blank">Criação de Sites</a> : <a href="http://www.trupe.net" target="_blank">Trupe Agência Criativa</a>
        			</p>
      			</div>
    		</div>
  		</div>

	</body>
</html>