laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('perfil', array('as' => 'perfil', 'uses' => 'PerfilController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));

Route::get('trocarIdioma/{lang?}', function($lang = ''){
	
	if($lang == 'pt')
		Session::put('idioma', 'pt');
	elseif($lang == 'en')
		Session::put('idioma', 'en');
	
	return Redirect::back();
});

Route::get('portfolio/{categoria?}/{projeto?}', array('as' => 'portfolio', 'uses' => 'PortfolioController@index'));
Route::get('clientes', array('as' => 'clientes', 'uses' => 'ClientesController@index'));
Route::get('parceiros', array('as' => 'parceiros', 'uses' => 'ParceirosController@index'));
Route::get('clippings/impressos/', array('as' => 'clippings.impressos', 'uses' => 'ClippingsImpressosController@index'));
Route::get('clippings/noshadow/{id}', array('as' => 'clippings.noshadow', 'uses' => 'ClippingsImpressosController@noShadow'));
Route::get('clippings/digitais', array('as' => 'clippings.digitais', 'uses' => 'ClippingsDigitaisController@index'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('banners', 'Painel\BannersController');
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('perfil', 'Painel\PerfilController');
    Route::resource('portfolio', 'Painel\PortfolioController');
    Route::resource('imagens', 'Painel\PortfolioImagensController');
    Route::resource('clientes', 'Painel\ClientesController');
    Route::resource('parceiros', 'Painel\ParceirosController');
    Route::resource('clippingImpresso', 'Painel\ClippingImpressoController');
    Route::resource('clippingImpressoImagens', 'Painel\ClippingImpressoImagensController');
    Route::resource('clippingDigital', 'Painel\ClippingDigitalController');
    Route::resource('contato', 'Painel\ContatoController');
});


Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);
	if(Auth::attempt($authvars)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

laravel/app/models/ClippingImpresso.php
<?php

class ClippingImpresso extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'clipping_impresso';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function imagens(){
    	return $this->hasMany('ClippingImpressoImagem', 'clipping_impresso_id');
    }
}

laravel/app/controllers/painel/AjaxController.php
<?php

// Namespace
namespace Painel;

// Core
use Request, Input, DB;

// Models

// BaseClass
use Controller;

class AjaxController extends Controller {

	public function __construct(){

	}

	/**
	 * Atualiza a ordem dos itens da tabela
	 *
	 * @return void
	 */
	function gravaOrdem(){
		/* Só aceita requisições feitas via AJAX */
		if(Request::ajax()){
			$menu = Input::get('data');
			$tabela = Input::get('tabela');

	        for ($i = 0; $i < count($menu); $i++) {
	        	DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
	        }
	        return json_encode($menu);
    	}else{
    		return "no-ajax";
    	}
	}

}

laravel/app/controllers/painel/BannersController.php
<?php

// Namespace
namespace Painel;

// Core
use View, Input, Str, Session, Redirect, File;

// Models
use Banner;

// Libs
use Imagine;

class BannersController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.banners.index')->with('banners', Banner::orderBy('ordem', 'ASC')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.banners.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{

		$banner = new Banner;

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');

			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/home/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));

			$imagem->move('assets/images/home/', $filename);
			$banner->imagem = $filename;

			$imagine = new Imagine\Gd\Imagine();
			$sizeOriginal = new Imagine\Image\Box(200,200);
			$mode    = Imagine\Image\ImageInterface::THUMBNAIL_OUTBOUND;

			ini_set('memory_limit','256M');
			$imagine->open('assets/images/home/'.$filename)
					->thumbnail($sizeOriginal, $mode)
					->save('assets/images/home/thumbs/'.$filename, array('quality' => 100));
		}
		$banner->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Banner criado com sucesso.');

		return Redirect::route('painel.banners.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.banners.edit')->with('banner', Banner::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$banner = Banner::find($id);

		if(Input::hasFile('imagem')){
			$imagem = Input::file('imagem');
			
			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/home/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));

			$imagem->move('assets/images/home/', $filename);
			$banner->imagem = $filename;

			$imagine = new Imagine\Gd\Imagine();
			$sizeOriginal = new Imagine\Image\Box(200,200);
			$mode    = Imagine\Image\ImageInterface::THUMBNAIL_OUTBOUND;

			ini_set('memory_limit','256M');
			$imagine->open('assets/images/home/'.$filename)
					->thumbnail($sizeOriginal, $mode)
					->save('assets/images/home/thumbs/'.$filename, array('quality' => 100));
		}
		$banner->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Banner alterado com sucesso.');

		return Redirect::route('painel.banners.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$banner = Banner::find($id);
		$banner->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Banner removido com sucesso.');

		return Redirect::route('painel.banners.index');
	}

}

laravel/app/controllers/painel/BaseAdminController.php
<?php

namespace Painel;

use Controller, View;

class BaseAdminController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

laravel/app/controllers/painel/ClientesController.php
<?php

namespace Painel;

use View, Input, Str, File, Session, Imagine, Redirect, Cliente;

class ClientesController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.clientes.index')->with('clientes', Cliente::orderBy('ordem')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.clientes.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Cliente;

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');
			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/clientes/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));
			$imagem->move('assets/images/clientes/', $filename);
			$object->imagem = $filename;

			ini_set('memory_limit','256M');

			$imagine = new Imagine\Gd\Imagine();
			$resizer = new \Rtablada\Images\ResizeAndPad($imagine);
			$image = $imagine->open('assets/images/clientes/'.$filename);
			$resizer->setSize(220, 160)->apply($image)->save('assets/images/clientes/'.$filename);			
		}

		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Cliente inserido com sucesso.');

		return Redirect::route('painel.clientes.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.clientes.edit')->with('cliente', Cliente::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Cliente::find($id);

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');
			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/clientes/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));
			$imagem->move('assets/images/clientes/', $filename);
			$object->imagem = $filename;

			ini_set('memory_limit','256M');

			$imagine = new Imagine\Gd\Imagine();
			$resizer = new \Rtablada\Images\ResizeAndPad($imagine);
			$image = $imagine->open('assets/images/clientes/'.$filename);
			$resizer->setSize(220, 160)->apply($image)->save('assets/images/clientes/'.$filename, array('quality' => 100));				
		}

		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Cliente alterado com sucesso.');

		return Redirect::route('painel.clientes.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Cliente::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Cliente removido com sucesso.');

		return Redirect::route('painel.clientes.index');
	}

}

laravel/app/controllers/painel/ClippingDigitalController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, ClippingDigital;

class ClippingDigitalController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.clippingDigital.index')->with('clipping', ClippingDigital::orderBy('ordem')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.clippingDigital.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new ClippingDigital;
		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->data = preg_replace("/(\d+)\D+(\d+)\D+(\d+)/","$3-$2-$1",Input::get('data'));
		$object->descricao_pt = Input::get('descricao_pt');
		$object->descricao_en = Input::get('descricao_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Clipping criado com sucesso.');

		return Redirect::route('painel.clippingDigital.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.clippingDigital.edit')->with('clipping', ClippingDigital::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = ClippingDigital::find($id);
		$object->titulo_pt = Input::get('titulo_pt');
		$object->titulo_en = Input::get('titulo_en');
		$object->data = preg_replace("/(\d+)\D+(\d+)\D+(\d+)/","$3-$2-$1",Input::get('data'));
		$object->descricao_pt = Input::get('descricao_pt');
		$object->descricao_en = Input::get('descricao_en');
		$object->link = Input::get('link');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Clipping alterado com sucesso.');

		return Redirect::route('painel.clippingDigital.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = ClippingDigital::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Clipping removido com sucesso.');

		return Redirect::route('painel.clippingDigital.index');
	}

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Contato;

class ContatoController extends BaseAdminController {

	protected $layout = 'painel.template';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('painel.contato.index')->with('contato', Contato::orderBy('id')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('painel.contato.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Contato;
		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Informações de contato criadas com sucesso.');

		return Redirect::route('painel.contato.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('painel.contato.edit')->with('contato', Contato::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Contato::find($id);
		$object->texto_pt = Input::get('texto_pt');
		$object->texto_en = Input::get('texto_en');
		$object->save();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Informações de contato alteradas com sucesso.');

		return Redirect::route('painel.contato.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Contato::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Informações de contato removidas com sucesso.');

		return Redirect::route('painel.contato.index');
	}

}

laravel/app/controllers/painel/HomeController.php
<?php

namespace Painel;

use View;

class HomeController extends BaseAdminController {

    protected $layout = 'painel.template';

	public function index()
	{
		$this->layout->content = View::make('painel.home');
	}

	public function login()
	{
		return View::make('painel.login');
	}

}

laravel/app/views/painel/clippingImpresso/edit.blade.php
@section('conteudo')

<div class="container">

  	<div class="page-header users-header">
    	<h2>
      		Alterar Clipping Impresso
    	</h2>
  	</div>

  	<div class="row">
    	<div class="span12 columns">

			{{ Form::open( array('route' => array('painel.clippingImpresso.update', $clipping->id), 'files' => true, 'method' => 'put', 'id' => 'form-edit-clip-imp') ) }}

				<label>
					Título - Versão em Português <img src="blank.gif" class="flag flag-br" ><br>
					<input type="text" name="titulo_pt" required required-message="Informe o Título da publicação!" value="{{$clipping->titulo_pt}}">	
				</label>

				<label>
					Título - Versão em Inglês <img src="blank.gif" class="flag flag-us"><br>
					<input type="text" name="titulo_en" required required-message="Informe o Título da publicação!" value="{{$clipping->titulo_en}}">	
				</label>

				<label>
					Data de Publicação<br>
					<input type="text" name="data" class="datepicker" required required-message="Informe a Data da publicação!" value="{{date('d/m/Y', strtotime($clipping->data))}}">
				</label>

				<label>Imagem<br>
				@if($clipping->capa)
					<img src="assets/images/clippings/thumbs/{{ $clipping->capa }}" style="width:200px;"><br>				
				@endif
				<input type="file" name="imagem"></label>

				<div class="form-actions">
		        	{{ Form::submit('Alterar', array('class' => 'btn btn-primary')) }}
		        	{{ Form::button('Voltar', array('class' => 'btn btn-voltar')) }}
		      	</div>
			{{ Form::close() }}

		</div>
	</div>

@stop

laravel/app/views/painel/clippingImpresso/form.blade.php
@section('conteudo')

<div class="container">

  	<div class="page-header users-header">
    	<h2>
      		Adicionar Clipping Impresso
    	</h2>
  	</div>

  	<div class="row">
    	<div class="span12 columns">

			{{ Form::open( array('route' => 'painel.clippingImpresso.store', 'files' => true, 'method' => 'post', 'id' => 'form-create-clip-imp') ) }}			

				<label>
					Título - Versão em Português <img src="blank.gif" class="flag flag-br" ><br>
					<input type="text" name="titulo_pt" required required-message="Informe o Título da publicação!">	
				</label>

				<label>
					Título - Versão em Inglês <img src="blank.gif" class="flag flag-us"><br>
					<input type="text" name="titulo_en" required required-message="Informe o Título da publicação!">	
				</label>

				<label>
					Data de Publicação<br>
					<input type="text" name="data" class="datepicker" required required-message="Informe a Data da publicação!">
				</label>

				<label>Imagem de Capa<br>
				<input type="file" name="imagem" required></label>

				<div class="form-actions">
		        	{{ Form::submit('Inserir', array('class' => 'btn btn-primary')) }}
		        	{{ Form::button('Voltar', array('class' => 'btn btn-voltar')) }}
		      	</div>
		      	
			{{ Form::close() }}

		</div>
	</div>

@stop

laravel/app/views/painel/clippingImpresso/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
	  <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
  @endif

	@if(Session::has('falha'))
		<div class="alert alert-block alert-error fade in"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('falha') }}</div>
	@endif

  	<div class="page-header users-header">
    	<h2>
      		Clippings Impressos <a href="{{ URL::route('painel.clippingImpresso.create') }}" class="btn btn-success"><i class="icon-plus-sign"></i> Adicionar Clipping</a>
    	</h2>
  	</div>

  	<div class="row">
    	<div class="span12 columns">
      		<table class="table table-striped table-bordered table-condensed">

          		<thead>
            		<tr>
                        <th>Título</th>
                        <th>Data</th>
                        <th>Capa</th>
                        <th>Páginas do Clipping</th>
              			<th><i class="icon-cog"></i></th>
            		</tr>
          		</thead>

          		<tbody>
            	@foreach ($clippings as $registro)

                	<tr class="tr-row" id="row_{{$registro->id}}">
                        <td>
                            PT: {{ $registro->titulo_pt }}
                            <br><br>                        
                            EN: {{ $registro->titulo_en }}
                        </td>
                        <td>
                            {{ date('d/m/Y', strtotime($registro->data)) }}
                        </td>
                        <td><img src="assets/images/clippings/thumbs/{{ $registro->capa }}" style="width:140px;"></td>
                        <td>
                            <a href="{{ URL::route('painel.clippingImpressoImagens.index', array('clipping_impresso_id' => $registro->id)) }}" class="btn btn-info">imagens</a>
                        </td>
                        <td class="crud-actions">
                  		    <a href="{{ URL::route('painel.clippingImpresso.edit', $registro->id ) }}" class="btn btn-primary">editar</a>

                            {{ Form::open(array('route' => array('painel.clippingImpresso.destroy', $registro->id), 'method' => 'delete')) }}
                                <button type="submit" href="{{ URL::route( 'painel.clippingImpresso.destroy', $registro->id) }}" class="btn btn-danger btn-delete">excluir</butfon>
                            {{ Form::close() }}
                        </td>
                	</tr>

            	@endforeach
          		</tbody>

        	</table>
    	</div>
  	</div>

@stop